=== AgriculturalModelExchangeInitiative/Crop2ML/AMEI-ModelUnit-Template.xsd
<?xml version="1.0" standalone="yes"?>
<xs:schema xmlns:ns1="AMEI-ModelUnit" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" id="ModelUnitDeclarative">
	<xs:element name="Attributes">
		<xs:complexType>
			<xs:sequence maxOccurs="1">
				<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Description" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="MaxVal" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="MinVal" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="DefVal" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Units" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="URL" type="xs:string" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="UnitTests">
		<xs:complexType>
			<xs:sequence maxOccurs="1">
				<xs:element name="UT" type="xs:string" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ModelUnit">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Algorithm" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Description">
					<xs:complexType>
						<xs:sequence maxOccurs="1">
							<xs:element name="Title" type="xs:string" minOccurs="1" maxOccurs="1"/>
							<xs:element name="Author" type="xs:string" minOccurs="1" maxOccurs="1"/>
							<xs:element name="Institution" type="xs:string" minOccurs="1" maxOccurs="1"/>
							<xs:element name="Reference" type="xs:string" minOccurs="1" maxOccurs="1"/>
							<xs:element name="Abstract" type="xs:string" minOccurs="1" maxOccurs="1"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Inputs" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Input" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Attributes" minOccurs="1" maxOccurs="1"/>
										<xs:element ref="UnitTests" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Outputs" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Output" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Attributes" maxOccurs="1"/>
										<xs:element ref="UnitTests" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Parameters" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Attributes" minOccurs="1" maxOccurs="1"/>
										<xs:element ref="UnitTests" minOccurs="1" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ModelUnitDeclarative" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="ModelUnit"/>
				<xs:element ref="Attributes"/>
				<xs:element ref="UnitTests"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AgriculturalModelExchangeInitiative/Crop2ML/Example.xml
<?xml version="1.0" encoding="UTF-8"?>
<ModelUnit xmlns="http://www.w3schools.com" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:schemaLocation="AMEI-ModelUnit-Template.xsd">
    <Description>
        <Title>Mean Value Example</Title>
        <Author>Andreas Enders</Author>
        <Institution>Uni Bonn</Institution>
        <Reference>some...</Reference>
        <Abstract>Extremely complex mean value calculator</Abstract>
    </Description>
    <Inputs>
        <Input>
            <Attributes>
                <Name>MaxTemp</Name>
                <Description>Maximum Temperature above ground (2m)</Description>
                <MaxVal>70</MaxVal>
                <MinVal>-40</MinVal>
                <DefVal>0</DefVal>
                <Units>°C</Units>
                <URL/>
            </Attributes>
            <UnitTests>
                <UT>10</UT>
                <UT>20</UT>
            </UnitTests>
        </Input>
        <Input>
            <Attributes>
                <Name>MinTemp</Name>
                <Description>Minimum Temperature above ground (2m)</Description>
                <MaxVal>70</MaxVal>
                <MinVal>-40</MinVal>
                <DefVal>0</DefVal>
                <Units>°C</Units>
                <URL/>
            </Attributes>
            <UnitTests>
                <UT>5</UT>
                <UT>15</UT>
            </UnitTests>
        </Input>
    </Inputs>
    <Ouputs>
        <Output>
            <Attributes>
                <Name>MeanTemp</Name>
                <Description>Mean Temperature calculated from Min and Max Temperature</Description>
                <MaxVal>70</MaxVal>
                <MinVal>-40</MinVal>
                <DefVal>0</DefVal>
                <Units>°C</Units>
                <URL/>
            </Attributes>
            <UnitTests>
                <UT>7.5</UT>
                <UT>17.5</UT>
            </UnitTests>
        </Output>
    </Ouputs>
    <Algorithm>MeanTemp = ( MaxTemp + MinTemp ) / 2</Algorithm>
</ModelUnit>
