=== AgriculturalModelExchangeInitiative/Crop2ML/ModelComposition.dtd
<!--
FILE : ModelComposition.dtd

CREATED : 2018

LAST MODIFIED : 2020

AUTHOR : Agricultural Models Exchange Initiative

DESCRIPTION : This document contains a DTD corresponding to the syntax rules
  defined in the Crop2ML model composite's Specification for Crop2ML 1.1. This
  specification is available at
    https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/crop2ml/master/ModelComposition.dtd

COPYRIGHT : (2018).
-->

<!ELEMENT ModelComposition (Description,Inputs?,Outputs?,Initialization?, Algorithm?,Composition,Parametersets?,Testsets?)>
<!ATTLIST ModelComposition
  name CDATA #REQUIRED
  id CDATA #REQUIRED
  timestep CDATA #IMPLIED
  version CDATA #IMPLIED>


<!ELEMENT Description (Title,Authors,Institution,URI?,Reference?,Abstract)>
<!ATTLIST Description>

<!ELEMENT Composition (Model+,Links)>

<!ELEMENT Model EMPTY>
<!ATTLIST Model
  name CDATA #REQUIRED
  id CDATA #REQUIRED
  filename CDATA #REQUIRED
  displayx CDATA #IMPLIED
  displayy CDATA #IMPLIED
  package_name CDATA #IMPLIED>

<!ELEMENT Links (InputLink*,InternalLink*,OutputLink*)>
<!ATTLIST Links>

<!ELEMENT Parametersets (Parameterset+)>
<!ATTLIST Parametersets>

<!ELEMENT Testsets (Testset+)>
<!ATTLIST Testsets>

<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title>

<!ELEMENT Authors (#PCDATA)>
<!ATTLIST Authors>

<!ELEMENT Institution (#PCDATA)>
<!ATTLIST Institution>

<!ELEMENT URI (#PCDATA)>
<!ATTLIST URI>

<!ELEMENT Reference (#PCDATA)>
<!ATTLIST Reference>

<!ELEMENT Abstract (#PCDATA)>
<!ATTLIST Abstract>

<!ELEMENT InputLink EMPTY>
<!ATTLIST InputLink
  target NMTOKEN #REQUIRED
  source NMTOKEN #REQUIRED>

<!ELEMENT InternalLink EMPTY>
<!ATTLIST InternalLink
  target NMTOKEN #REQUIRED
  source NMTOKEN #REQUIRED>

<!ELEMENT OutputLink EMPTY>
<!ATTLIST OutputLink
  source NMTOKEN #REQUIRED
  target NMTOKEN #REQUIRED>

<!ELEMENT Inputs (Input)+>
<!ATTLIST Inputs>

<!ELEMENT Input EMPTY>
<!ATTLIST Input
  name NMTOKEN #REQUIRED
  datatype (STRING|STRINGARRAY|STRINGLIST|DATE|DATEARRAY|DATELIST|DOUBLE|DOUBLEARRAY|DOUBLELIST|INT|INTARRAY|INTLIST|BOOLEAN) #REQUIRED 
  description CDATA #REQUIRED
  default CDATA #IMPLIED
  max CDATA #IMPLIED
  min CDATA #IMPLIED
  inputtype (variable|parameter) #REQUIRED
  parametercategory (constant|species|genotypic|soil|private) #IMPLIED
  variablecategory (state|rate|auxiliary) #IMPLIED
  unit CDATA #IMPLIED
  uri CDATA #IMPLIED>

<!ELEMENT Outputs (Output*)>
<!ATTLIST Outputs>

<!ELEMENT Output EMPTY>
<!ATTLIST Output
  name NMTOKEN #REQUIRED
  datatype (STRING|STRINGARRAY|STRINGLIST|DATE|DATEARRAY|DATELIST|DOUBLE|DOUBLEARRAY|DOUBLELIST|INT|INTARRAY|INTLIST|BOOLEAN) #REQUIRED 
  description CDATA #REQUIRED
  max CDATA #IMPLIED
  min CDATA #IMPLIED
  variablecategory (state|rate|auxiliary) #IMPLIED
  unit CDATA #IMPLIED
  uri CDATA #IMPLIED>

<!ELEMENT Initialization (#PCDATA)>
<!ATTLIST Initialization
	name CDATA #REQUIRED
	language CDATA #REQUIRED
  filename CDATA #IMPLIED>
  	
<!ELEMENT Algorithm (#PCDATA)>
<!ATTLIST Algorithm
  language CDATA #REQUIRED
  platform CDATA #IMPLIED
  filename CDATA #IMPLIED
  function CDATA #IMPLIED>
  
<!ELEMENT Parameterset (Param*)>
<!ATTLIST Parameterset
  description CDATA #REQUIRED
  name NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Testset (Test+)>
<!ATTLIST Testset
  description CDATA #REQUIRED
  name CDATA #REQUIRED
  parameterset NMTOKEN #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Test (InputValue*, OutputValue+)>
<!ATTLIST Test
  description CDATA #IMPLIED
  name CDATA #REQUIRED
  uri CDATA #IMPLIED>

<!ELEMENT Param (#PCDATA) >
<!ATTLIST Param name CDATA #REQUIRED >

<!ELEMENT InputValue (#PCDATA) >
<!ATTLIST InputValue name CDATA #REQUIRED >

<!ELEMENT OutputValue (#PCDATA) >
<!ATTLIST OutputValue name CDATA #REQUIRED >
<!ATTLIST OutputValue description CDATA #IMPLIED >
<!ATTLIST OutputValue precision CDATA #IMPLIED >

=== AgriculturalModelExchangeInitiative/Crop2ML/example/Phenology_Model/Phenology_ModelComposite.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Model PUBLIC " " "https://raw.githubusercontent.com/AgriculturalModelExchangeInitiative/xml_representation/master/ModelComposition.dtd">
<ModelComposition name="Phenology" id="Sirius.Phenology" version="001" timestep = "1">
  <Description>
    <Title>Phenology</Title>
    <Authors>Pierre MARTRE</Authors>
    <Institution>INRA</Institution>
    <Reference>Crop stage development</Reference>
    <Abstract>see documentation</Abstract>
  </Description>
  <Composition>
    <Model name="Phyllochron" id="Phyllochron.Phenology" filename="Example_Sirius_Phyllochron.xml" />
    <Model name="PhylSowingDateCorrection" id="PhylSowingDateCorrection.Phenology" filename="Example_Sirius_CalculatePhylSowingDateCorrection.xml" />
    <Model name="RegisterZadok" id="RegisterZadok.Phenology" filename="Example_Sirius_RegisterZadok.xml" />
    <Model name="ShootNumber" id="ShootNumber.Phenology" filename="Example_Sirius_ShootNumber.xml" />
    <Model name="UpdateLeafFlag" id="UpdateLeafFlag.Phenology" filename="Example_Sirius_UpdateLeafFlag.xml" />
    <Model name="UpdatePhase" id="UpdatePhase.Phenology" filename="Example_Sirius_UpdatePhase.xml" />
    <Model name="LeafNumber" id="LeafNumber.Phenology" filename="Example_Sirius_LeafNumber.xml" />
    <Model name="VernalizationProgress" id="VernalizationProgress.Phenology" filename="Example_Sirius_VernalizationProgress.xml" />
    <Model name="IsMomentRegistredZC_39" id="IsMomentRegistredZC_39.Phenology" filename="Example_Sirius_IsMomentRegistredZC39.xml" />
 	<Model name="CumulTTFRom" id="CumulTTFRom.Phenology" filename="Example_Sirius_CumulTTFRom.xml" />
 	<Model name="CalendarModule" id="CalendarModule.Phenology" filename="Example_Sirius_CalendarModule.xml" />

  <Links>
      <InputLink target="Phyllochron.LeafNumber" source="LeafNumber" />
      <InputLink target="Phyllochron.Lincr" source="Lincr" />
      <InputLink target="Phyllochron.Ldecr" source="Ldecr" />
      <InputLink target="Phyllochron.Pdecr" source="Pdecr" />
      <InputLink target="Phyllochron.Pincr" source="Pdecr" />
      <InputLink target="Phyllochron.LAI" source="LAI" />
      <InputLink target="Phyllochron.PTQ" source="PTQ" />      
      <InputLink target="Phyllochron.GAI" source="GAI" />            
      <InputLink target="Phyllochron.pastMaxAI" source="pastMaxAI" />
      <InputLink target="Phyllochron.Kl" source="Kl" />
      <InputLink target="Phyllochron.aPTQ" source="aPTQ" />           
      <InputLink target="Phyllochron.PhylPTQ1" source="PhylPTQ1" />
      <InputLink target="Phyllochron.P" source="P" />
      <InputLink target="Phyllochron.choosePhyllUse" source="choosePhyllUse" />
      <InputLink target="IsMomentRegistredZC_39.calendar" source="calendar" />
      <InputLink target="PhylSowingDateCorrection.SowingDay" source="SowingDay" />
      <InputLink target="PhylSowingDateCorrection.SDsa_sh" source="SDsa_sh" />
      <InputLink target="PhylSowingDateCorrection.P"source="P" />      
      <InputLink target="PhylSowingDateCorrection.SDws" source="SDws" />
      <InputLink target="PhylSowingDateCorrection.SDsa_nh" source="SDsa_nh" />      
      <InputLink target="PhylSowingDateCorrection.Rp" source="Rp" />
      <InputLink target="CumulTTFRom.calendar" source="calendar" />
      <InputLink target="CumulTTFRom.SwitchMaize" source="SwitchMaize" />
      <InputLink target="CumulTTFRom.cumulTT" source="cumulTT" />
      <InputLink target="VernalizationProgress.rhoDensityAir" source="IsVernalizable" />
      <InputLink target="VernalizationProgress.Vernaprog" source="Vernaprog" />      
      <InputLink target="VernalizationProgress.DeltaTT" source="DeltaTT" />
      <InputLink target="VernalizationProgress.MinTvern" source="MinTvern" />
      <InputLink target="VernalizationProgress.tauAlpha" source="tauAlpha" />      
      <InputLink target="VernalizationProgress.IntTvern" source="IntTvern" />      
      <InputLink target="VernalizationProgress.VAI" source="VAI" />      
      <InputLink target="VernalizationProgress.VBEE" source="VBEE" />      
      <InputLink target="VernalizationProgress.MinDL" source="MinDL" />
      <InputLink target="VernalizationProgress.MaxDL" source="MaxDL" />
      <InputLink target="VernalizationProgress.DayLength" source="DayLength" />
      <InputLink target="VernalizationProgress.MaxTvern" source="MaxTvern" />
      <InputLink target="VernalizationProgress.LeafNumber" source="LeafNumber" />
      <InputLink target="VernalizationProgress.PNini" source="PNini" />
      <InputLink target="VernalizationProgress.MinFinalNumber" source="MinFinalNumber" />
      <InputLink target="VernalizationProgress.AMXLFNO" source="currentdate" />
      <InputLink target="VernalizationProgress.cumulTT" source="calendar" />
      <InputLink target="UpdatePhase.Dse" source="Dse" />
      <InputLink target="UpdatePhase.IsVernalizable" source="IsVernalizable" />
      <InputLink target="UpdatePhase.PFLLAnth" source="PFLLAnth" />
      <InputLink target="UpdatePhase.Dcd" source="Dcd" />
      <InputLink target="UpdatePhase.Dgf" source="Dgf" />
      <InputLink target="UpdatePhase.Degfm" source="Degfm" />
      <InputLink target="UpdatePhase.MaxDL" source="MaxDL" />
      <InputLink target="UpdatePhase.IgnoreGrainMaturation" source=" IgnoreGrainMaturation" />
      <InputLink target="UpdatePhase.PHEADANTH" source=" PHEADANTH" />
      <InputLink target="UpdatePhase.SwitchMaize" source=" SwitchMaize" />
      <InputLink target="UpdatePhase.choosePhyllUse" source=" choosePhyllUse" />
      <InputLink target="UpdatePhase.P" source=" P" />
      <InputLink target="UpdatePhase.DayLength" source=" DayLength" />
      <InputLink target="UpdatePhase.SLDL" source=" SLDL" />
      <InputLink target="UpdatePhase.cumulTT" source="cumulTT" />
      <InputLink target="UpdatePhase.LeafNumber" source="LeafNumber" />
      <InputLink target="UpdatePhase.GrainCumulTT" source="GrainCumulTT" />
      <InputLink target="UpdatePhase.GAI" source="GAI" />
      <InputLink target="UpdatePhase.phase" source="phase" />
      <InputLink target="UpdatePhase.hasLastPrimordiumAppeared" source="hasLastPrimordiumAppeared" />
      <InputLink target="UpdatePhase.FinalLeafNumber" source="FinalLeafNumber" />
      <InputLink target="LeafNumber.LeafNumber" source="LeafNumber" />
      <InputLink target="LeafNumber.HasFlagLeafLiguleAppeared" source="HasFlagLeafLiguleAppeared" />
      <InputLink target="LeafNumber.SwitchMaize" source="SwitchMaize" />
      <InputLink target="LeafNumber.DeltaTT" source="DeltaTT" />
      <InputLink target="LeafNumber.Leaf_tip_emerg" source="Leaf_tip_emerg" />
      <InputLink target="LeafNumber.atip" source="atip" />
      <InputLink target="LeafNumber.Nlim" source=" Nlim" />
      <InputLink target="LeafNumber.k_bl" source="k_bl" />
      <InputLink target="LeafNumber.cumulTTPhenoMaizeAtEmergence" source="cumulTTPhenoMaizeAtEmergence" />
      <InputLink target="LeafNumber.cumulTT" source="cumulTT" />
      <InputLink target="UpdateLeafFlag.HasFlagLeafLiguleAppeared" source="HasFlagLeafLiguleAppeared" />
      <InputLink target="UpdateLeafFlag.currentdate" source="currentdate" />
      <InputLink target="UpdateLeafFlag.cumulTT" source="cumulTT" />
      <InputLink target="RegisterZadok.currentdate" source=currentdate" />
      <InputLink target="RegisterZadok.cumulTT" source="cumulTT" />
      <InputLink target="RegisterZadok.slopeTSFLN" source="slopeTSFLN" />
      <InputLink target="RegisterZadok.TSFLN" source="TSFLN" />
      <InputLink target="RegisterZadok.Der" source="Der" />
      <InputLink target="RegisterZadok.currentZadokStage" source="currentZadokStage" />
      <InputLink target="CalendarModule.currentdate" source="currentdate" />
      <InputLink target="CalendarModule.cumulTT" source="cumulTT" />
      <InputLink target="ShootNumber.CanopyShootNumber" source="CanopyShootNumber" />
      <InputLink target="ShootNumber.SowingDensity" source="SowingDensity" />
      <InputLink target="ShootNumber.TargetFertileShoot" source="TargetFertileShoot" />
      <InputLink target="ShootNumber.tilleringProfile" source="tilleringProfile" />
      <InputLink target="ShootNumber.leafTillerNumberArray" source="leafTillerNumberArray" />
      <InputLink target="ShootNumber.TillerNumber" source="TillerNumber" />            

      <InternalLink target="Phyllochron.FixPhyll" source="PhylSowingDateCorrection.FixPhyll" />      
      <InternalLink target="UpdatePhase.Vernaprog" source="VernalizationProgress.Vernaprog" />
      <InternalLink target="UpdatePhase.MinFinalNumber" source="VernalizationProgress.MinFinalNumber" />
      <InternalLink target="UpdatePhase.isMomentRegistredZC_39" source="IsMomentRegistredZC_39.isMomentRegistredZC_39" />
      <InternalLink target="UpdatePhase.cumulTTFromZC_39" source="CumulTTFRom.cumulTTFromZC_39" />
      <InternalLink target="UpdatePhase.cumulTTFromZC_91" source="CumulTTFRom.cumulTTFromZC_91" />
      <InternalLink target="UpdatePhase.FixPhyll" source="PhylSowingDateCorrection.FixPhyll" />
      <InternalLink target="UpdatePhase.Phyllochron" source="Phyllochron.Phyllochron" />
      <InternalLink target="LeafNumber.Phyllochron" source="Phyllochron.Phyllochron" />
      <InternalLink target="LeafNumber.phase" source="UpdatePhase.phase" />
      <InternalLink target="UpdateLeafFlag.LeafNumber" source="LeafNumber.LeafNumber" />
      <InternalLink target="UpdateLeafFlag.FinalLeafNumber" source="UpdatePhase.FinalLeafNumber" />
      <InternalLink target="UpdateLeafFlag.calendar" source="VernalizationProgress.calendar" />
      <InternalLink target="UpdateLeafFlag.phase" source="UpdatePhase.phase"/>
      <InternalLink target="RegisterZadok.FinalLeafNumber" source="UpdatePhase.FinalLeafNumber" />
      <InternalLink target="RegisterZadok.LeafNumber" source="LeafNumber.LeafNumber" />
      <InternalLink target="RegisterZadok.calendar" source="UpdateLeafFlag.calendar" />
